---
# Plays common to the Deploy and Destroy blocks are first
#- name: My Task
#    k8s:
#      src:


# Deploy block is run as long as the finalizer has not set teardown=true
- name: Deploy
  when: teardown is undefined
  block:

  - name: Deploy couchbase operator
    k8s:
      definition: "{{ lookup('template', 'couchbase-operator.yaml.j2') }}"

  # Can't get the 'until' below to behave
  - name: Take a break
    pause: 
      seconds: 10

  - name: Get pods list
    k8s_facts:
      kind: Pod
      namespace: "{{ operator_namespace }}"
    register: pods
    #until: '"couchbase-operator" in (pods | json_query("resources[].metadata.name"))'
    retries: 10
    delay: 5

  #- debug:
  #    msg: "PODS DEBUG: {{ pods | json_query('resources[].metadata.name') }}"

  - name: Get couchbase operator pod
    set_fact:
      cb_op_pod: "{{ item.metadata.name }}"
    with_items: "{{ pods.resources }}"
    when: '"couchbase-operator" in item.metadata.name'

  #- debug:
  #    msg: "CB_OP_POD DEBUG: {{ cb_op_pod }}"

  - name: Wait for Couchbase Operator to be Running....
    k8s_facts:
      kind: Pod
      namespace: "{{ operator_namespace }}"
      name: "{{ cb_op_pod }}"
    register: cb_op_status
    until: "'Running' in (cb_op_status | json_query('resources[].status.phase'))"
    retries: 10
    delay: 10

  # For BZ 1678285
  # https://bugzilla.redhat.com/show_bug.cgi?id=1678285
  - name: Apply RBAC for couchbase operator
    k8s:
      definition: "{{ lookup('template', 'couchbase-operator-rbac.yaml.j2') }}"

  - name: Create the Couchbase Auth Secret
    k8s:
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: cb-cluster-auth
          namespace: "{{ operator_namespace }}"
        type: Opaque
        data:
          username: QWRtaW5pc3RyYXRvcg==
          password: cGFzc3dvcmQ=

  # Pre-pull the image to avoid CB operator timeout
  - name: Pre-Pull Couchbase Container Image
    k8s:
      definition:
        kind: Job
        apiVersion: batch/v1
        metadata:
          name: cb-image-load
          namespace: "{{ operator_namespace }}"
        spec:
          template:
            spec:
              containers:
                - name: cb-image-load
                  image: "{{ pod_base_image }}:{{ pod_version }}"
                  command: ['/bin/true']
              restartPolicy: Never
              imagePullSecrets:
                - name: "{{ pull_secret_name }}"
          backoffLimit: 4

  - name: Wait for Pre-Pull Job to Succeed
    k8s_facts:
      kind: Job
      api_version: batch/v1
      namespace: "{{ operator_namespace }}"
      name: cb-image-load
    register: cb_image_load
    until: "cb_image_load | json_query('resources[].status.succeeded')"
    retries: 60
    delay: 10

  - name: Launch Couchbase Cluster via Operator
    k8s:
      definition: "{{ lookup('template', 'couchbase-cluster.yaml.j2') }}"

  - name: Wait for Couchbase Cluster to be Up; This may take a while...
    k8s_facts:
      kind: CouchbaseCluster
      api_version: couchbase.com/v1
      namespace: "{{ operator_namespace }}"
      name: cb-benchmark
    register: cbc
    until: cbc | json_query('resources[].status.conditions.Available.status') and cbc | json_query('resources[].status.members.ready[]') | length == couchbase.servers.size
    #60 retries with 10 second delays should result in a 10 minute wait time
    retries: 60
    delay: 10

  # For use with YCSB, the username must match the bucket name
  # See https://github.com/brianfrankcooper/YCSB/issues/1062#issuecomment-344716601
  - name: Set Password for the Default Bucket
    uri:
      url: "http://cb-benchmark.{{ operator_namespace }}.svc.cluster.local:8091/settings/web"
      method: POST
      # This is the default couchbase admin user/pass
      user: Administrator
      password: password
      body_format: form-urlencoded
      body:
        username: default
        password: "{{ default_bucket_password }}"
        port: 8091

  - name: Set Couchbase Service Hostname
    set_fact:
      couchbase_hostname: "cb-benchmark.{{ operator_namespace }}.svc.cluster.local"

  - name: Globalize Default Bucket Password Variable
    set_fact:
      default_bucket_password: "{{ default_bucket_password }}"


# Destroy block is run when the finalizer has set teardown=true
- name: Destroy
  when: teardown is defined
  block:

  - name: Get pre-pull pod
    k8s_facts:
      kind: Pod
      namespace: "{{ operator_namespace }}"
      label_selectors:
        - job-name = cb-image-load
    register: img_pod

  - name: Destroy pre-pull pod
    k8s:
      kind: Pod
      namespace: "{{ operator_namespace }}"
      name: "{{ item.metadata.name }}"
      state: absent
    with_items: "{{ img_pod.resources }}"

  - name: Destroy couchbase cluster via operator
    k8s:
      definition: "{{ lookup('template', 'couchbase-cluster.yaml.j2') }}"
      state: absent

  - name: Get couchbase operator CSV
    k8s_facts:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      namespace: "{{ operator_namespace }}"
    register: csvs

  - name: Destroy couchbase operator CSV
    k8s:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      namespace: "{{ operator_namespace }}"
      name: "{{ item.metadata.name }}"
      state: absent
    with_items: "{{ csvs.resources }}"
    when: "'couchbase' in item.metadata.name"

  - name: Destroy RBAC for couchbase operator
    k8s:
      definition: "{{ lookup('template', 'couchbase-operator-rbac.yaml.j2') }}"
      state: absent

  - name: Get couchbase cluster endpoints
    k8s_facts:
      kind: Endpoint
      namespace: "{{ operator_namespace }}"
    register: endpoints

  - name: Destroy couchbase cluster endpoints
    k8s:
      kind: Endpoint
      namespace: "{{ operator_namespace }}"
      name: "{{ item.metadata.name }}"
      state: absent
    with_items: "{{ endpoints.resources }}"
    when: '"couchbase" in item.metadata.name'
