apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-operator
  namespace: builder-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      name: infra-operator
  template:
    metadata:
      labels:
        name: infra-operator
    spec:
      serviceAccountName: infra-operator
      containers:
        - name: infra-operator
          # Replace this with the built image name
          image: quay.io/cloud-bulldozer/infra-operator:master
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ANSIBLE_VERBOSITY
              value: "4"
            - name: OPERATOR_NAME
              value: "infra-operator"
