kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-operator
  namespace: builder-infra
subjects:
- kind: ServiceAccount
  name: infra-operator
  namespace: builder-infra
roleRef:
  kind: Role
  name: infra-operator
  apiGroup: rbac.authorization.k8s.io
