kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-operator
subjects:
- kind: ServiceAccount
  name: infra-operator
  namespace: builder-infra
roleRef:
  kind: ClusterRole
  name: infra-operator
  apiGroup: rbac.authorization.k8s.io
