apiVersion: builder.cloudbulldozer.io/v1alpha1
kind: Infra
metadata:
  name: postgres-infra
  namespace: builder-infra
spec:
  infrastructure:
    name: postgres
    args:
      clusters: 3 # number of postgres clusters
      cluster_size: 1 # number of pods per postgres cluster
      #storageclass: # uses the sc with the annotation storageclass.kubernetes.io/is-default-class: "true" if the option is not specified or commented
      storagesize: 10Gi # default value if option not specified
      port: 5432 # default value if option not specified
