apiVersion: builder.cloudbulldozer.io/v1alpha1
kind: Infra
metadata:
  name: couchbase-infra
  namespace: builder-infra
spec:
  infrastructure:
    name: couchbase
    args:
      servers:
        # Typical deployment size is 3
        size: 3
      storage:
        use_persistent_storage: False
        class_name: "rook-ceph-block"
        volume_size: 10Gi
      deployment:
        # These are deployment defaults from roles/couchbase-infra/defaults
        # that can be overridden here.
        #
        ## For Generic K8s w/ Upstream OLM and Marketplace Defaults
        #olm_catalog: "operatorhubio-catalog"
        #olm_namespace: "olm"
        #cb_operator_package: "couchbase-enterprise"
        #pod_base_image: "docker.io/library/couchbase"
        #pod_version: "enterprise-5.5.2"
        #default_bucket_password: "password"
        #
        ## For OpenShift v3 w/ Upstream OLM and Marketplace Defaults
        #olm_catalog: "operatorhubio-catalog"
        #olm_namespace: "olm"
        #cb_operator_package: "couchbase-enterprise"
        #pod_base_image: "registry.connect.redhat.com/couchbase/server"
        #pod_version: "5.5.4-1"
        #default_bucket_password: "password"
        #pull_secret_name: "rhsecret"
        #
        ## For OpenShift v4 w/ Built-In OLM and Marketplace
        #olm_catalog: "operatorhubio-catalog"
        #olm_namespace: "openshift-operator-lifecycle-manager"
        #cb_operator_package: "couchbase-enterprise-certified"
        #pod_base_image: "registry.connect.redhat.com/couchbase/server"
        #pod_version: "5.5.4-1"
        #default_bucket_password: "password"
        #pull_secret_name: "rhsecret"
