apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: postgres-infra
  namespace: ripsaw
spec:
  infrastructure:
    name: postgres
    args:
      servers:
        # Typical deployment size is 3
        size: 1
      storage:
        # persistent storage volume is required
        class_name: "standard"
        volume_size: 1G
      deployment:
        # These are deployment defaults from roles/postgres-infra/defaults
        # that can be overridden here.
        #
        ## For Generic K8s w/ Upstream OLM
        #postgres_operator_package: "postgres-operator"
        #olm_catalog: operatorhubio-catalog
        #olm_namespace: olm
        #
        ## For OpenShift v3 w/ Upstream OLM
        #postgres_operator_package: TODO
        #olm_catalog: TODO
        #olm_namespace: TODO
        #
        ## For OpenShift v4 w/ Built-In OLM
        #postgres_operator_package: "postgres-operator"
        #olm_catalog: operatorhubio-catalog
        #olm_namespace: openshift-operator-lifecycle-manager
